[project]
name = "newTrackon"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
    "requests==2.32.4",
    "tornado==6.5.1",
    "Flask==3.1.1",
    "dnspython==2.7.0",
]

[dependency-groups]
dev = [
    "ruff==0.11.2",
    "mypy==1.15.0",
    "types-requests==2.32.0.20250328",
]

[tool.setuptools.packages.find]
exclude = ["data*"]

[tool.ruff]
line-length = 130

[tool.mypy]
python_version = "3.13"
# strict = true
